/**
 * Loreno Domain Types & Data Contracts (Hackathon FounderRace 2026)
 * Strict TypeScript types with zero `any` for AI validation and end-to-end stability.
 */

/**
 * Individual flashcard with front (question/concept) and back (answer/definition)
 */
export interface Flashcard {
  id?: string;
  deck_id?: string;
  front: string;
  back: string;
  order_index?: number;
  created_at?: string;
}

/**
 * Persisted deck entity in Supabase table `decks`
 */
export interface Deck {
  id: string;
  user_id: string;
  title: string;
  subject?: string | null;
  summary?: string | null;
  initial_quiz_question?: string | null;
  image_url?: string | null;
  image_urls?: string[] | null;
  created_at?: string;
  updated_at?: string;
  flashcards?: Flashcard[];
}

/**
 * Structured output generated by Gemini 1.5 Flash Vision OCR
 */
export interface ScanResult {
  title: string;
  subject: string;
  summary: string;
  initial_quiz_question: string;
  flashcards: Array<{
    front: string;
    back: string;
  }>;
}

/**
 * API response contract for `/api/scan`
 */
export interface ScanApiResponse {
  success: boolean;
  deckId?: string;
  data?: ScanResult;
  imageUrl?: string;
  imageUrls?: string[];
  error?: string;
}

/**
 * Client-side notebook item displayed in the dashboard
 */
export interface NotebookItem {
  id: string;
  title: string;
  subject: string;
  emoji: string;
  date: string;
  sourceCount: number;
  deck: ScanResult;
  imageUrl?: string | null;
  imageUrls?: string[] | null;
}

/**
 * Chat message for the AI Exam Tutor
 */
export interface TutorChatMessage {
  role: "user" | "model";
  text: string;
  isStreaming?: boolean;
}
